### import pandas as pd
df = pd.DataFrame({"name":["appwars","python","ml","sql","aws"]})

In [2]:
df

      name
0  appwars
1   python
2       ml
3      sql
4      aws

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder ()

In [5]:
le.fit_transform(df["name"])

array([0, 3, 2, 4, 1])

In [6]:
df["en_name"] = le.fit_transform(df["name"])

In [7]:
df

      name  en_name
0  appwars        0
1   python        3
2       ml        2
3      sql        4
4      aws        1