In [11]:
import pandas as pd 
dataset = pd.read_csv(r"C:\Users\himanshu bagoria\OneDrive\Desktop\new loan dataset\new loan dataset\test_Y3wMUE5_7gLdaTN.csv")

# one hot encording
#import pandas as pd
dataset = pd.read_csv(r"C:\Users\himanshu bagoria\OneDrive\Desktop\new loan dataset\new loan dataset\test_Y3wMUE5_7gLdaTN.csv")

In [12]:
dataset.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban

In [13]:
dataset.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [14]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)

C:\Users\himanshu bagoria\AppData\Local\Temp\ipykernel_17468\1904562844.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)

In [15]:
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace = True)

C:\Users\himanshu bagoria\AppData\Local\Temp\ipykernel_17468\4286777439.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Married"].fillna(dataset["Married"].mode()[0],inplace = True)

In [16]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [17]:
en_data = dataset[["Gender","Married"]]

In [18]:
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True       False         True
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
362          False         True       False         True
363          False         True       False         True
364          False         True        True        False
365          False         True       False         True
366          False         True        True        False

[367 rows x 4 columns]

In [19]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  367 non-null    bool
 1   Gender_Male    367 non-null    bool
 2   Married_No     367 non-null    bool
 3   Married_Yes    367 non-null    bool
dtypes: bool(4)
memory usage: 1.6 KB

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder()

In [22]:
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 734 stored elements and shape (367, 4)>

In [23]:
ohe = OneHotEncoder()

In [24]:
ar=ohe.fit_transform(en_data).toarray()

In [25]:
pd.DataFrame(ar,columns=["Gender_Female","Gender_Male","Married_No","Married_Yes"])

     Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         0.0          1.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
362            0.0          1.0         0.0          1.0
363            0.0          1.0         0.0          1.0
364            0.0          1.0         1.0          0.0
365            0.0          1.0         0.0          1.0
366            0.0          1.0         1.0          0.0

[367 rows x 4 columns]